name: ci

on:
  push:
    branches: 
      - main

jobs:
  docker-build-manager:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-manager
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
          push: true
          tags: |
            ghcr.io/duckfullstop/nixos-longhorn-manager:v1.1.0
  
  docker-build-instance-manager:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-instance-manager
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
          push: true
          tags: |
            ghcr.io/duckfullstop/nixos-longhorn-instance-manager:v1_20201216
